#!/bin/bash

USER=$1

if [[ -z "$USER" ]]; then
  echo "must pass in github username"
  exit 1
fi

echo "Adding keys for $USER"

echo "#### $USER ####" >> ~/.ssh/authorized_keys
curl https://github.com/$USER.keys >> ~/.ssh/authorized_keys
echo "#### END $USER ####" >> ~/.ssh/authorized_keys
