#!/bin/bash

source lib/prompt.sh

prompt "Github User to give access" "" "GITHUB_USER"
prompt "Host" "" "HOST"

sudo apt-get update
sudo apt-get htop
bash authorize-github-user $GITHUB_USER
bash set-hostname $HOST
bash install-docker
bash install-docker-extras
