#!/bin/bash

docker run \
  --volume=/:/rootfs:ro \
  --volume=/var/run:/var/run:rw \
  --volume=/sys:/sys:ro \
  --volume=/var/lib/docker/:/var/lib/docker:ro \
  --publish=8080 \
  -e VIRTUAL_HOST=cadvisor.* \
  --detach=true \
  --name=cadvisor \
  google/cadvisor:latest
