#!/bin/bash

docker inspect dockergen > /dev/null 2>&1

if [[ "$?" == 0 ]]; then
  docker stop dockergen
  docker rm dockergen
fi

docker run \
  --name dockergen \
  -d \
  --restart always \
  --volume '/var/run/docker.sock:/tmp/docker.sock:ro' \
  --volumes-from nginx \
  firstandthird/nginx-gen:0.0.6
