#!/bin/bash

docker run -d \
  --name letsencrypt \
  -v /etc/certs:/etc/nginx/certs:rw \
  --volumes-from nginx \
  -v /var/run/docker.sock:/var/run/docker.sock:ro \
  -e NGINX_DOCKER_GEN_CONTAINER=dockergen \
  alastaircoote/docker-letsencrypt-nginx-proxy-companion
  #jrcs/letsencrypt-nginx-proxy-companion
