#!/bin/bash

docker run \
  --name nginx \
  -d \
  -p '80:80' \
  -p '443:443' \
  --restart always \
  --volume '/etc/nginx/conf.d' \
  --volume '/etc/certs:/etc/nginx/certs:ro' \
  --volume '/usr/share/nginx/html' \
  --volume '/etc/nginx/vhost.d' \
  firstandthird/nginx:0.0.1

docker run \
  --name dockergen \
  -d \
  --restart always \
  --volume '/var/run/docker.sock:/tmp/docker.sock:ro' \
  --volumes-from nginx \
  firstandthird/nginx-gen:0.0.5
