#!/bin/bash

docker run \
  --name nginx \
  -d \
  -p '80:80' \
  -p '443:443' \
  --restart always \
  --volume '/etc/nginx/conf.d' \
  --volume '/etc/certs:/etc/nginx/certs:ro' \
  --volume '/usr/share/nginx/html' \
  --volume '/etc/nginx/vhost.d' \
  firstandthird/nginx:0.0.1

bash dockergen
