#!/bin/bash

source lib/prompt.sh

prompt "How big?" "30M" "SIZE"
prompt "Container Name" "nginx" "CONTAINER"

CMD="echo 'client_max_body_size $SIZE;' > /etc/nginx/conf.d/size.conf"
docker exec $CONTAINER sh -c "${CMD}"
docker kill -s SIGHUP $CONTAINER
