#!/bin/bash



if [[ "$1" == "swarm" ]]; then
  docker service create \
    --name portainer \
    --publish 9000:9000 \
    --constraint 'node.role == manager' \
    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    portainer/portainer \
    -H unix:///var/run/docker.sock
else
  docker run \
    -d \
    -p 9000 \
    --name portainer \
    -e VIRTUAL_HOST=portainer.* \
    -v /var/run/docker.sock:/var/run/docker.sock \
    portainer/portainer
fi

