#!/bin/bash

source lib/prompt.sh

prompt "Domain" "" "DOMAIN"

docker network inspect traefik-net > /dev/null 2>&1
if [[ "$?" == 1 ]]; then
  echo "Creating network"
  docker network create --driver=overlay traefik-net
fi

docker service create \
  --name traefik \
  --constraint=node.role==manager \
  --publish 80:80 --publish 8080:8080 \
  --mount type=bind,source=/var/run/docker.sock,target=/var/run/docker.sock \
  --network traefik-net \
  traefik \
  --docker \
  --docker.swarmmode \
  --docker.domain="$DOMAIN" \
  --docker.watch \
  --web 
