#!/bin/bash

source lib/prompt.sh

prompt "Github User to give access" "" "GITHUB_USER"
prompt "Host" "" "HOST"

sudo apt-get update
sudo apt-get htop
bash server/authorized_keys $GITHUB_USER
bash server/set-hostname $HOST
bash server/install-docker
bash server/install-docker-extras
