#!/bin/bash

source lib/prompt.sh

prompt "Name" "" "SERVER_NAME"
prompt "Instance Type" t2.medium "INSTANCE_TYPE"
prompt "Size" 50 "SERVER_SIZE"
prompt "Region" us-east-1 "AWS_REGION"

docker-machine create \
  --driver amazonec2 \
  --amazonec2-instance-type $INSTANCE_TYPE \
  --amazonec2-root-size $SERVER_SIZE \
  --amazonec2-region $AWS_REGION \
  $SERVER_NAME
