#!/bin/bash

source lib/prompt.sh

prompt "Name" "" "SERVER_NAME"
prompt "Instance Type" t2.medium "INSTANCE_TYPE"
prompt "Key Name" "" "KEY_NAME"
prompt "Size" 50 "SERVER_SIZE"
prompt "Region" us-east-1 "AWS_REGION"
prompt "Image AMI" "ami-40d28157" "SERVER_IMAGE"
prompt "Security Groups" "" "SECURITY_GROUPS"
prompt "Subnet" "" "SUBNET"


OUTPUT=$(aws ec2 run-instances \
  --key-name $KEY_NAME \
  --image-id $SERVER_IMAGE \
  --instance-type $INSTANCE_TYPE \
  --security-group-ids $SECURITY_GROUPS \
  --subnet-id $SUBNET \
  --associate-public-ip-address \
  --block-device-mapping "[ { \"DeviceName\": \"/dev/sda1\", \"Ebs\": { \"VolumeSize\": $SERVER_SIZE } } ]")

if [[ $? -ne 0 ]]; then
  echo $OUTPUT
  exit 1
fi

INSTANCE_ID=$(echo $OUTPUT | jq -r ".Instances[0].InstanceId")

echo $OUTPUT
echo $INSTANCE_ID

aws ec2 create-tags --resources $INSTANCE_ID --tags "Key=Name,Value=$SERVER_NAME"

bash aws/ec2-until-running $INSTANCE_ID

echo "Instance $INSTANCE_ID is now running"
bash aws/ec2-dns $SERVER_NAME
