#!/bin/bash

NAME=$1

if [[ -z "$NAME" ]]; then
  echo "must pass in server name"
fi

aws ec2 describe-instances --filters Name=tag:Name,Values="$NAME" --query "Reservations[].Instances[].PublicDnsName" --output text
