#!/bin/bash

source lib/prompt.sh

prompt "Name" "" "SERVER_NAME"
prompt "Instance Type" t2.medium "INSTANCE_TYPE"
prompt "Size" 50 "SERVER_SIZE"
prompt "Region" us-east-1 "AWS_REGION"
prompt "Image AMI" "ami-40d28157" "SERVER_IMAGE"
prompt "Security Groups" "" "SECURITY_GROUPS"
prompt "Subnet" "" "SUBNET"


OUTPUT=$(aws ec2 run-instances \
  --image-id $SERVER_IMAGE \
  --instance-type $INSTANCE_TYPE \
  --security-group-ids $SECURITY_GROUPS \
  --subnet-id $SUBNET \
  --associate-public-ip-address \
  --block-device-mapping "[ { \"DeviceName\": \"/dev/sda1\", \"Ebs\": { \"VolumeSize\": $SERVER_SIZE } } ]")

INSTANCE_ID=$(echo $OUTPUT | jq -r ".Instances[0].InstanceId")

echo $OUTPUT
echo $INSTANCE_ID

aws ec2 create-tags --resources $INSTANCE_ID --tags "Key=Name,Value=$SERVER_NAME"


STATUS=""
while [ $STATUS != "running" ]; do
  STATUS=$(aws ec2 describe-instance-status --instance-id $INSTANCE_ID | jq -r ".InstanceStatuses[0].InstanceState.Name")
  sleep 5
done
